_episodes/01-software-development-intro.md
* Remove Makefile from `ls -l` output
* Remove `$` from commands - it was somewhat confusing, making it look like `$` was part of the command.
=> Fix minor typos and simplify syntax

_episodes/00-setting-the-scene.md
These commands may happen to appear to do what is being asked.
The result will depend on where the parent and children folders are located.
=> Clarify `cd ~` and `cd -`

_episodes/02-ides.md
Comment form pilot #2
Renato] After opening a project PyCharm warns that no Python interpreter has been set.
This is covered later in the lesson so perhaps a forward reference to “Adding a Python Interpreter in PyCharm” would be helpful.
[Renato] version control in pycharm: Minor formatting typo in “comprehensive subset”
[Renato] Build-in -> built-in
[Renato] Adding a Python interpreter in PyCharm: Conda 3 defaults to 3.8 now so some references to 3.7 may be out of date.
[Renato] Configuring PyCharm with Anaconda: Confusing use of Anaconda vs Conda. Anaconda already includes “numpy” and “matplotlib” so adding those to the environment was unexpected here.
[Pip] PyCharm: The shortcut bindings can differ if people have preconfigured pycharm to use for example vim bindings
[Sam] There is a …
=> Addressed comments from internal pilot #2 on IDEs.

_episodes/05-coding-convention.md
[Renato] I would avoid most of the explanations on alternative ways of indenting the code and breaking long lines in favor of introducing tools such as autopep8, yapf or the popular black (https://github.com/psf/black now officially recognized as a Python Software Foundation project).
Most of the lesson would become, code before formatted with black” and “code after” while explaining what black does to respect PEP8.
Black is supported by PyCharm - https://black.readthedocs.io/en/stable/editor_integration.html
[Renato] While I find code style quite important, many modern languages bundle tools in the standard lib to validate or even enforce a given style (Rust, Go, …). This solves the subjective argument that comes with style guides.
Other tools worth mentioning in this context: flake8, …
=> Addressed comments from internal pilot #2 on code convention.

_episodes/10-section1-intro.md, _episodes/11-software-development.md, _episodes/15-coding-conventions.md, index.md
Fixing a few broken internal links (on and between pages), typos, and a slight issue with the output of `ls` not including the `__init__.py` file.
I added the `__init__.py` file to the existing example for consistency with Aleks other `ls` outputs, instead of using an 'accurate' `ls` output. I think this level of mild forgery is OK.
=> Fixing broken internal links, a few typos in section 1.

_episodes/12-virtual-environments.md, _episodes/13-ides.md, setup.md
The python version is a little out of date - adjusted using @smason's wording from issue #111, and made the 'how to exit the python terminal' section a little more robust.
The virtual environment section places a lot of emphasis on looking at the installed packages with `ls`. This isn't a common use case, so tweaked it to emphasise `pip freeze` and `pip list`.
=> Python Version & Virtual Environment Tweaks

_episodes/14-collaboration-using-git.md
Personal access tokens are introduced, and caching credentials is suggested, but this is likely to be a bit inconvenient given the 15 minute timeout. Added a section on storing credentials and ameliorating the security risk with token timeouts.
=> Added section on account security

_episodes/14-collaboration-using-git.md
This removes guidance that it is safe to delete a branch called `main` from a repository used to build a GitHub Pages website. 
Especially since GitHub made it so much easier to use static site generators other than Jekyll to build websites, a lot of repositories use `main` as their default branch. These projects have GitHub Actions or similar workflows, set up to build source HTML files that can then be served via GitHub Pages. Those source files are usually found in a `gh-pages` branch (though not always - `docs` is another common name for such branches), but this certainly does not mean it would be safe to delete `main` on these projects.
As an example: since transition to the new lesson infrastructure, almost all of The Carpentries official lesson repositories use `main` as the …
=> remove hint about deleting main on Pages repositories

setup.md
On Windows, the Python version 3 installation from https://www.python.org/downloads/ does not come with a python3.exe file. See here: https://github.com/python/cpython/issues/99185
Added some Windows specific instructions (call python instead)
=> Update setup with Windows specific instructions

_episodes/21-automatically-testing-software.md
Addresses #150 - I agree it would be a good idea to have an explanation, particularly given that unittest is installed by default as part of Python. Added a brief callout to the unit testing intro episode explaining some of the reasons why pytest was chosen over unittest, with a link to more information.
=> Fixes #150 - add explanation for using pytest over unittest

_episodes/23-continuous-integration-automated-testing.md
This PR makes two changes:
* adds an explanation of using the pipe to concatenate multi line strings
* Use a consistent array indentation between the examples explaining YAML and the example GitHub Actions
I think there is a reasonable case to simply get rid of the introduction to YAML. The structure is designed to be somewhat intuitive, and most people will be creating GitHub Actions workflows by copy-pasting snippets to get their CI to do what they want, and therefore don't need a deep understanding of the YAML syntax. 
This addresses #215
=> GitHub Actions / YAML Section Consistency

index.md
Small reorganisation of the home page. Moved learning objectives above prerequisites.
=> Moved LOs are above prereqs.

_episodes/12-virtual-environments.md, _extras/common-issues.md, setup.md
=> Added a note on python hanging issue on Windows

_episodes/12-virtual-environments.md, _episodes/13-ides.md, _episodes/16-verifying-code-style-linters.md, _episodes/21-automatically-testing-software.md, _episodes/22-scaling-up-unit-testing.md, _episodes/23-continuous-integration-automated-testing.md, _episodes/43-software-release.md, _extras/common-issues.md, _extras/databases.md, _extras/vscode.md
Switch to "python3 -m" to install pip instead of "pip3 install". 
Fixes #276.
=> Switch to "python3 -m" to install pip

_episodes/11-software-project.md, _episodes/14-collaboration-using-git.md, fig/git-feature-branch.svg, setup.md
Improved the wording around SSH and key authentication with GitHub.
1. Stressing more that we recommend SSH for authorised operations with GitHub (e.g. push)
2. Removed discussion around GitHub requiring personal access tokens with HTTPS (old news)
3. Fixed some awkward wording.
4. Used this as an opportunity to fix the git feature diagram to have a more correct timeline for "feature y" branch.
Fixes #243.
=> Improved wording around SSH and key authn with GitHub

setup.md
Old instructions referred to RSA algorithm even though we switched to Ed25519.
=> Fixed setup for key pairs and GitHub

_episodes/43-software-release.md
Fixes #268 
I found one other reference in the 'Setting up our Poetry Config` introduction, where it's explicitly mentioned as part of the packaging history, so I left that one in.
Other than that, I did not find any other prior mentions of `setup.py` in the lesson material.
=> Remove setup.py reference in poetry episode

.github/workflows/website.yml
As per @douglowe's fix: https://github.com/carpentries-incubator/python-intermediate-development-earth-sciences/pull/38 - this is needed for the lesson to build.
=> Fixing Ruby version for website workflow

_config.yml, _episodes/32-software-design.md, _episodes/33-code-decoupling-abstractions.md, _episodes/34-code-refactoring.md, _extras/object-oriented-programming.md, _extras/procedural-programming.md, _extras/programming-paradigms.md
=> Swap refactoring and abstractions episodes 

README.md, _config.yml, _extras/guide.md
=> Update to instructor notes

_episodes/21-automatically-testing-software.md
Fixes #364: replacing `git branch -c test-suite` with `git switch -c test-suite`
=> change 'branch -c' to 'switch -c' for test-suite

_episodes/15-coding-conventions.md
Some of the characters were backticked (displayed as if code), while others were between single quotes. They are now consistently backticked
=> Consistent confusing characters examples

episodes/21-automatically-testing-software.md, episodes/31-software-requirements.md, episodes/41-code-review.md, episodes/51-managing-software.md
=> Add a callout to remind learners to activate virtual env

episodes/23-continuous-integration-automated-testing.md
Yanking this downstream from our UKAEA fork thanks to @JezSw
=> Expand Python version range for build matrix and where the version variable is used

episodes/12-virtual-environments.md, episodes/13-ides.md, episodes/16-verifying-code-style-linters.md, episodes/21-automatically-testing-software.md, episodes/22-scaling-up-unit-testing.md, episodes/23-continuous-integration-automated-testing.md, slides/section_1_setting_up_environment.md, slides/section_4_collaborative_soft_dev.md
As explained in #278, it is often a point of friction that learners don't have the local project installed in their virtual environment. Even though a lot of this can be alleviated by using `python -m <command>`, there are still deficits in that this command *must* be executed from the top level of the project where the `inflammation/` source directory is located.
As I also mention in that issue, it is standard practice to locally install the package you are working on and do so with an editable install. At the level of this course, I think this is an essential practice to impart.
Closes #278 
Please also see https://github.com/carpentries-incubator/python-intermediate-inflammation/pull/41 for the relevant change needed for the learner repo.
=> Add explanations around installing our project locally

episodes/41-code-review.md
=> Fix un-rendered callout by changing it to a note

episodes/14-collaboration-using-git.md
Do not state that .gitignore has to be in the project root, because that would be false. However, state that this is a common location.
=> 14-collaboration-using-git.md: .gitignore not only project root

episodes/23-continuous-integration-automated-testing.md
I don't see a reason to use the date format DD-MM-YYYY in the example. Thus: use the standard iso YYYY-MM-DD format instead to show good practice in action.
=> use iso-formated date in example

episodes/23-continuous-integration-automated-testing.md
@pgmccann and I were teaching this today at https://st-andrews-carpentries.github.io/2025-05-27-standrews/ and noticed that DOB's of two climbers are the same.
=> Correct Purtscheller's DOB

learners/common-issues.md, slides/section_3_software_dev_process.md, slides/section_4_collaborative_soft_dev.md
These are some changes I made to the slides when delivering section 3/4 of the course in March. 
Changes are:
* Fixed some out-of-date SSH addresses that still point to the UKAEA repository.
* Removed a slide at the end of section 3 that instructs students to merge their working branch into `develop`. This caused some confusion in section 4, where, in the first exercise, students are asked to create a pull request containing their changes, but they'd already merged them. 
Looking at the notes now, I see that it says to open a PR into `main` not `develop`, but there was definitely some confusion on the day. It may have been my fault!
I need to check through the course notes to find the right answer here, but don't have the time right now. I'll try to have a look in the next few days.
=> Fix discrepancy in git instructions

episodes/41-code-review.md
In the "Raising a Pull Request" section of Episode 4.1, the target branch for the PR is set to be `main`. If we are following "gitflow" like in the rest of the lesson, this should be `develop`. This has directly caused confusion in our runs of the course and I don't think it should cause any issues, although there might be some merge conflicts because the `develop` branch has had quite a bit done to it by this point, and the `feature-std-dev` branch is quite far behind.
I will report back how it goes, but if someone is able to resolve this more immediately, that would be appreciated.
Resolves #458
=> Switch code review PR target to be develop branch rather than main
