carpentries-incubator/python-intermediate-development

_episodes/03-virtual-environments.md
Comments from pilot #2:
[Sam] Introduction does not introduce virtual environments. Possible reworking:
When we configured a Python interpreter and set of modules for our project in PyCharm in the previous episode, what we did was create a virtual environment. Virtual environments aren’t just a feature of PyCharm, though, and you can also use them through the command line shell. In this episode, we go into virtual environments in more detail, showing what they are, how and why you’d use them.
[Sam] Running Scripts From Command Line -> Running Scripts From The Command Line
[Pip] Running scripts from command line: Why do we activate a python environment within the terminal when we could switch tabs to a python console and get a richer environment?
[Renato] This sentence gets a bit lost in …
=> Addressed comments from internal pilot #2 on virtual environments.

_episodes/05-coding-convention.md, _episodes/06-collaboration-using-git.md, _episodes/35-improvement-through-feedback.md
Comments from pilot #2
[Pip] I think the new convention is to use ‘main’ instead of ‘master’ for the primary git branch due to master having negative cultural inferences.
[Renato] Git refresher: “we first have add” -> “we first have to add”
[Pip] Lots of the YAML example boxes are headed with bash which may confuse people
[Kamilla][Douglas] Git refresher: git add patient.db inflammation/models.py  <<Should Be>> git add patientdb.py inflammation/models.py
[Renato] Git Branches: I think this was mentioned but “master” -> “main” for branch name. Figures would need to be updated as well which is considerably more work.
[Renato] Updating Branches: Perhaps remove one of the functions from models.py and add it here. Code could be provided here or in the form of a (mandatory) exercise.
[Renato] …
=> Addressed comments from internal pilot #2 on collaborative development.

_episodes/32-preparing-software-reuse.md
As commented on the course, it would be a good idea for learners to do a final merge of develop into main. This PR adds a small section to the reuse episode at the end for this.
=> Add final merge into main

index.md
Tried to make it cleared that our target audience are people who have been applying basic software development skills for a while. In line with modifications to the "Setting the scene" episode (https://github.com/softwaresaved/python-intermediate-development/pull/72) and future updates to include an overview/umbrella diagram in "Setting the scene".
=> Making target audience clearer. Tightened and shortened intro.

_episodes/01-section1-intro.md, _episodes/02-software-development.md, _episodes/03-ides.md, _episodes/04-virtual-environments.md, _episodes/05-coding-conventions.md, _episodes/06-collaboration-using-git.md, _episodes/16-diagnosing-issues-improving-robustness.md, _episodes/25-software-design.md, fig/inflammation-dataset.svg, index.md
- Swapped getting template code repo with software architecture bits
- reduced the size of text on MVC
- moved some examples into the MVC exercise
=> Reorganisation of the MVC and software architecture bits in section 1

_config.yml
using "incubator" for the `carpentries:` variable
=> switching to carpentries incubator styling

_episodes/00-setting-the-scene.md
<details>
<summary><strong>Instructions</strong></summary>
Thanks for contributing! :heart:
If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!
Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.
You may …
=> very small typo

_episodes/12-virtual-environments.md
=> Added a callout to address two usages of pip

_episodes/13-ides.md
pooling together small language suggestions for the [section 1 ide episode](https://carpentries-incubator.github.io/python-intermediate-development/13-ides/index.html)
=> Small language changes to Section 1 IDE episode

_episodes/16-verifying-code-style-linters.md
Some small changes to the [section one episode on linters](https://carpentries-incubator.github.io/python-intermediate-development/16-verifying-code-style-linters/index.html)
=> small changes to sec1, style linters

_episodes/12-virtual-environments.md
Working on putting together this PR with small language changes in the [Section 1 virtual environments episode](https://carpentries-incubator.github.io/python-intermediate-development/12-virtual-environments/index.html)
=> Lang edits to sect 1 - virt env episode

_episodes/34-functional-programming.md
<details>
<summary><strong>Instructions</strong></summary>
Thanks for contributing! :heart:
If this contribution is for instructor training, please email the link to this contribution to
checkout@carpentries.org so we can record your progress. You've completed your contribution
step for instructor checkout by submitting this contribution!
Keep in mind that **lesson maintainers are volunteers** and it may take them some time to
respond to your contribution. Although not all contributions can be incorporated into the lesson
materials, we appreciate your time and effort to improve the curriculum. If you have any questions
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at team@carpentries.org.
You may …
=> Pull request to address inaccuracy in the Pure Functions Exercise

_episodes/12-virtual-environments.md
=> Adding windows variation info

_episodes/23-continuous-integration-automated-testing.md
Discovered this in the pilot today
=> missing quote

setup.md
Fixes https://github.com/carpentries-incubator/python-intermediate-development/issues/180
=> Update link to python version status

_episodes/34-functional-programming.md
Thank you for spotting this @douglowe - please check the fix.
=> Converting map iterator to a list. Fixes #187.

_episodes/35-object-oriented-programming.md
It is an anti-pattern to use exceptions to manage control flow. In this specific case it would be bad as an observation without a 'day' would silently just make the next observation start at day 0. In general it is a bad practice as is essentially a goto so can make code harder to follow and can make debugging harder (if auto breaking on exceptions).
I don't think it is worth going into detail in the course about this topic, but at least we won't be giving examples the don't exemplify best practices.
=> Don't use exception handling for control flow in OOP example

_episodes/22-scaling-up-unit-testing.md
Adding one of the key (IMO) advantages of TDD. Seemed easier to raise the PR than raise an issue, so if you don't feel this is an improvement then feel free to close this PR.
=> Add advantage to TDD about ensuring the tests fail

README.md
Swapped order of sentences to make sure self-learning mode is introduced and explained.
=> Swapped order of sentences

AUTHORS
=> Add Thomas Kiley to authors

_episodes/15-coding-conventions.md
A bunch of small tweaks to the naming section of 1.5 coding conventions. Mostly to make the recommendations more explicit and opinionated, but also hopefully with less unnecessary information that will probably be immediately forgotten. 
Addresses #218
=> Make naming convention more opinionated

GOVERNANCE.md, README.md
Suggestion for the governance process, based on https://github.com/carpentries/lesson-development-training/blob/main/GOVERNANCE.md by @tobyhodges.
=> Create governance process

setup.md
=> Added a line about WSL not being supported

_episodes/14-collaboration-using-git.md, _episodes/15-coding-conventions.md, _episodes/16-verifying-code-style-linters.md, _episodes/21-automatically-testing-software.md, _episodes/23-continuous-integration-automated-testing.md, _episodes/24-diagnosing-issues-improving-robustness.md, _episodes/41-code-review.md, _episodes/42-software-reuse.md, fig/git-lifecycle.svg, setup.md
=> Replacing checkout with switch

_episodes/12-virtual-environments.md
=> Added a callout about -m flag

_episodes/32-software-design.md
=> Explained which std we mean

_episodes/13-ides.md
=> Earlier explanation of run configurations

_episodes/34-functional-programming.md
=> Typo fix. Fixes #281.

_episodes/36-architecture-revisited.md
=> Fix links to persistence episodes

_episodes/15-coding-conventions.md
=> Comment about develop branch

_episodes/42-software-reuse.md
=> Update GitHub Actions badge url

GOVERNANCE.md, README.md
Rotation of lead maintainers: https://github.com/carpentries-incubator/python-intermediate-development/issues/308
=> Lead maintainer's term of service

_episodes/23-continuous-integration-automated-testing.md
=> Update checkout and setup-python actions to v4

_episodes/24-diagnosing-issues-improving-robustness.md
=> Add information about pdb as an alternate debugging option

setup.md
=> Small fixes for setup

_episodes/32-software-design.md, _episodes/35-software-architecture.md
=> Refactor software design/software architecture learning narrative

_extras/common-issues.md
=> Improved fix for winpty issue. Fixes #190.

_episodes/32-software-architecture-design.md, _episodes/33-code-decoupling-abstractions.md, _episodes/34-code-refactoring.md, _episodes/35-software-architecture-revisited.md
Revisions based on review of the reworked section 3.
=> Section 3 rework - develop branch review revisions 

_episodes/23-continuous-integration-automated-testing.md
Solves #351 
Not sure if the base branch is the correct one. In case just let me know, I'll change it @anenadic
=> clarify the mail.yml file structure when matrices are added

_episodes/43-software-release.md
=> Use group --dev notation poetry

README.md, _config.yml, _episodes/23-continuous-integration-automated-testing.md
=> Added callout about failed builds

_config.yml, _episodes/12-virtual-environments.md, _episodes/13-ides.md, _episodes/16-verifying-code-style-linters.md, _episodes/17-section1-optional-exercises.md, _episodes/22-scaling-up-unit-testing.md, _episodes/25-section2-optional-exercises.md, _extras/guide.md
Fixes #258 for section 1 and 2.
This adds a new episode at the end of the section with optional exercises. We could also choose to have 1 episode as extra material with optional exercises for all episodes.
Current status: section 1 and 2 done. This can be reviewed now or wait for all sections to have optional exercises, I think it would be nice to review now to make sure this is in line with thoughts the other contributors
=> Add optional exercises for section 1 and 2

_episodes/12-virtual-environments.md, _episodes/13-ides.md, _episodes/16-verifying-code-style-linters.md, _episodes/17-section1-optional-exercises.md, _episodes/22-scaling-up-unit-testing.md, _episodes/25-section2-optional-exercises.md, _extras/guide.md
Just some markdown formatting changes and a few corrections to the optional exercises for sections 1 and 2. If you want to see these changes more easily, just focus in on the last commit at the tip of this branch https://github.com/carpentries-incubator/python-intermediate-development/commit/ebe4ec99e92e0a412b2340659dabdbdd41d98d26
=> Further formatting edits for optional exercises coming from NeSC

_episodes/21-automatically-testing-software.md, _episodes/22-scaling-up-unit-testing.md, _episodes/24-diagnosing-issues-improving-robustness.md, _extras/databases.md, _extras/object-oriented-programming.md
=> Move imports outside of test method code

_episodes/43-software-release.md
=> Fix header of 4.3

README.md
=> Add link to GitLab version of the lesson in README

learners/common-issues.md
The URL in the command mixed up ssh-style and https-style, not working for any in the end.
=> fix git command

episodes/15-coding-conventions.md, episodes/21-automatically-testing-software.md, slides/section_1_setting_up_environment.md
Hi 👋 
I'm preparing to teach this course at the University of Birmingham so I'm currently working through the material. I'll probably open a few more issues and PRs in the next few weeks, but this is a nice simple one to start with.
=> Fix Sphinx typos and typo in 21-automatically-testing-software

episodes/43-software-release.md
Fixes #457
Newer poetry has newer output
=> Update pdm init output for PEP621 compliant poetry
